import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const photos = (slug: string, count: number) =>
  Array.from(
    { length: count },
    (_, i) => `https://picsum.photos/seed/${slug}-${i + 1}/800/600`
  );

const PROPERTIES = [
  {
    source: "seed",
    source_id: "seed-001",
    source_url: "#",
    address: "1247 Burma Ave",
    normalized_address: "1247 burma ave",
    city: "Gillette",
    state: "WY",
    zip: "82716",
    lat: 44.2894,
    lng: -105.5012,
    beds: 3,
    baths: 2,
    sqft: 1620,
    lot_size_sqft: 7840,
    year_built: 1998,
    price: 285000,
    financing_types: ["subject_to"],
    down_payment: null,
    monthly_payment: 1089,
    option_fee: null,
    lease_term_months: null,
    interest_rate: 3.25,
    balloon_months: null,
    raw_description:
      "3 bed / 2 bath home in great condition near schools and shopping. This is a subject-to opportunity — take over the seller's existing mortgage at 3.25% with a balance of approximately $245,000. PITI payment is $1,089/mo. Seller has equity and needs a quick close. House was updated in 2019 (new roof, HVAC, kitchen counters). Attached 2-car garage. Motivated seller — call or text today.",
    parsed_terms: {
      financing_types: ["subject_to"],
      down_payment: null,
      monthly_payment: 1089,
      option_fee: null,
      lease_term_months: null,
      interest_rate: 3.25,
      balloon_months: null,
      confidence: 0.95,
    },
    photos: photos("burma-ave", 4),
    contact_name: "Mike Patterson",
    contact_phone: "(307) 555-0142",
    contact_email: null,
    first_seen_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-002",
    source_url: "#",
    address: "823 Country Club Rd",
    normalized_address: "823 country club rd",
    city: "Gillette",
    state: "WY",
    zip: "82716",
    lat: 44.3012,
    lng: -105.4934,
    beds: 2,
    baths: 1,
    sqft: 952,
    lot_size_sqft: 6200,
    year_built: 1985,
    price: 195000,
    financing_types: ["rent_to_own"],
    down_payment: null,
    monthly_payment: 1200,
    option_fee: 5000,
    lease_term_months: 24,
    interest_rate: null,
    balloon_months: null,
    raw_description:
      "Cute starter home in quiet neighborhood — perfect rent-to-own opportunity! $5,000 option fee gets you in the door, then $1,200/mo with 25% of each payment credited toward your purchase. 24-month lease term. Purchase price locked at $195,000 today — no bank qualifying required. Great for buyers rebuilding credit or with non-traditional income. Freshly painted interior, new water heater 2023. Owner is motivated.",
    parsed_terms: {
      financing_types: ["rent_to_own"],
      down_payment: null,
      monthly_payment: 1200,
      option_fee: 5000,
      lease_term_months: 24,
      interest_rate: null,
      balloon_months: null,
      confidence: 0.97,
    },
    photos: photos("country-club", 3),
    contact_name: "Sarah Hendricks",
    contact_phone: "(307) 555-0217",
    contact_email: "sarah.hendricks@example.com",
    first_seen_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-003",
    source_url: "#",
    address: "456 W Lakeway Rd",
    normalized_address: "456 w lakeway rd",
    city: "Gillette",
    state: "WY",
    zip: "82718",
    lat: 44.2856,
    lng: -105.5234,
    beds: 4,
    baths: 2.5,
    sqft: 2240,
    lot_size_sqft: 12150,
    year_built: 2003,
    price: 320000,
    financing_types: ["seller_financing"],
    down_payment: 30000,
    monthly_payment: 2100,
    option_fee: null,
    lease_term_months: null,
    interest_rate: 7.0,
    balloon_months: null,
    raw_description:
      "Beautiful 4-bed home on large lot — owner will carry the financing. $30,000 down, then $2,100/mo at 7% interest over 30 years. No bank needed! Ideal for self-employed buyers, those with non-traditional income, or anyone who needs a fast close. Formal dining room, large master suite with walk-in closet, 3-car garage, and a covered back patio. Clean title, no HOA. Serious inquiries only — must have down payment available.",
    parsed_terms: {
      financing_types: ["seller_financing"],
      down_payment: 30000,
      monthly_payment: 2100,
      option_fee: null,
      lease_term_months: null,
      interest_rate: 7.0,
      balloon_months: null,
      confidence: 0.98,
    },
    photos: photos("lakeway-rd", 5),
    contact_name: "Dave Kowalski",
    contact_phone: "(307) 555-0389",
    contact_email: null,
    first_seen_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-004",
    source_url: "#",
    address: "1891 Westover Rd",
    normalized_address: "1891 westover rd",
    city: "Gillette",
    state: "WY",
    zip: "82716",
    lat: 44.2978,
    lng: -105.4867,
    beds: 2,
    baths: 1,
    sqft: 920,
    lot_size_sqft: 5500,
    year_built: 1979,
    price: 175000,
    financing_types: ["lease_option"],
    down_payment: null,
    monthly_payment: 975,
    option_fee: 3500,
    lease_term_months: 36,
    interest_rate: null,
    balloon_months: null,
    raw_description:
      "Lease option available on this cozy 2 bed / 1 bath home. $3,500 option fee, $975/mo rent — part of every payment builds equity toward your purchase. 36-month option period gives you time to qualify for traditional financing while locking in today's price of $175,000. Property is in solid shape with updated electrical. Fenced backyard, covered parking. Perfect first-time buyer situation.",
    parsed_terms: {
      financing_types: ["lease_option"],
      down_payment: null,
      monthly_payment: 975,
      option_fee: 3500,
      lease_term_months: 36,
      interest_rate: null,
      balloon_months: null,
      confidence: 0.96,
    },
    photos: photos("westover-rd", 3),
    contact_name: null,
    contact_phone: "(307) 555-0461",
    contact_email: null,
    first_seen_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-005",
    source_url: "#",
    address: "314 S Douglas Hwy",
    normalized_address: "314 s douglas hwy",
    city: "Gillette",
    state: "WY",
    zip: "82716",
    lat: 44.2823,
    lng: -105.5156,
    beds: 4,
    baths: 3,
    sqft: 3180,
    lot_size_sqft: 18500,
    year_built: 2008,
    price: 445000,
    financing_types: ["wrap"],
    down_payment: 40000,
    monthly_payment: 2850,
    option_fee: null,
    lease_term_months: null,
    interest_rate: 5.5,
    balloon_months: 60,
    raw_description:
      "Wrap-around mortgage available on this executive home. Seller will wrap their existing note — buyer pays $2,850/mo to seller at 5.5%. $40,000 down. Balloon payment due in 60 months (5 years), giving buyer time to refinance when rates improve. 4 bed / 3 bath, vaulted ceilings, gourmet kitchen with granite, finished basement, 3-car heated garage on nearly half an acre. This is a premium property with premium creative financing.",
    parsed_terms: {
      financing_types: ["wrap"],
      down_payment: 40000,
      monthly_payment: 2850,
      option_fee: null,
      lease_term_months: null,
      interest_rate: 5.5,
      balloon_months: 60,
      confidence: 0.94,
    },
    photos: photos("douglas-hwy", 5),
    contact_name: "Tom & Lisa Brennan",
    contact_phone: "(307) 555-0534",
    contact_email: "brennan.re@example.com",
    first_seen_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-006",
    source_url: "#",
    address: "702 E 8th St",
    normalized_address: "702 e 8th st",
    city: "Gillette",
    state: "WY",
    zip: "82716",
    lat: 44.2945,
    lng: -105.4998,
    beds: 3,
    baths: 2,
    sqft: 1820,
    lot_size_sqft: 9200,
    year_built: 1994,
    price: 290000,
    financing_types: ["novation"],
    down_payment: 20000,
    monthly_payment: 1650,
    option_fee: null,
    lease_term_months: null,
    interest_rate: 4.0,
    balloon_months: null,
    raw_description:
      "Novation deal — we will substitute you as the borrower on the existing FHA loan at 4.0% interest. $20,000 down payment. Your name goes on the existing mortgage — fully legal and transparent process. Monthly payment is $1,650 including taxes and insurance. 3 bed / 2 bath in established neighborhood. Mature trees, big yard, covered front porch. Seller is relocating for work and needs to close in 30 days.",
    parsed_terms: {
      financing_types: ["novation"],
      down_payment: 20000,
      monthly_payment: 1650,
      option_fee: null,
      lease_term_months: null,
      interest_rate: 4.0,
      balloon_months: null,
      confidence: 0.93,
    },
    photos: photos("8th-st", 4),
    contact_name: "Greg Olson",
    contact_phone: "(307) 555-0612",
    contact_email: null,
    first_seen_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-007",
    source_url: "#",
    address: "1563 Boxelder Rd",
    normalized_address: "1563 boxelder rd",
    city: "Gillette",
    state: "WY",
    zip: "82718",
    lat: 44.3056,
    lng: -105.5312,
    beds: 4,
    baths: 2,
    sqft: 2420,
    lot_size_sqft: 21780,
    year_built: 2001,
    price: 365000,
    financing_types: ["subject_to", "seller_financing"],
    down_payment: 15000,
    monthly_payment: 1780,
    option_fee: null,
    lease_term_months: null,
    interest_rate: 3.75,
    balloon_months: 84,
    raw_description:
      "Flexible financing available — seller willing to do either subject-to (take over existing loan at 3.75%) or seller-carry at the same rate. Down payment as low as $15,000. Payment approximately $1,780/mo. 7-year balloon. Country-feel property on half-acre lot, 4 bedrooms, bonus room could be office or 5th bed, 2-car attached plus large shop/garage detached. Well and septic — no city utility bills. 15 minutes from downtown Gillette.",
    parsed_terms: {
      financing_types: ["subject_to", "seller_financing"],
      down_payment: 15000,
      monthly_payment: 1780,
      option_fee: null,
      lease_term_months: null,
      interest_rate: 3.75,
      balloon_months: 84,
      confidence: 0.91,
    },
    photos: photos("boxelder-rd", 5),
    contact_name: "Randy Simmons",
    contact_phone: "(307) 555-0723",
    contact_email: "randy.simmons@example.com",
    first_seen_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-008",
    source_url: "#",
    address: "978 Rolling Hills Dr",
    normalized_address: "978 rolling hills dr",
    city: "Gillette",
    state: "WY",
    zip: "82716",
    lat: 44.2867,
    lng: -105.4823,
    beds: 3,
    baths: 2,
    sqft: 1440,
    lot_size_sqft: 7920,
    year_built: 1991,
    price: 215000,
    financing_types: ["rent_to_own", "lease_option"],
    down_payment: null,
    monthly_payment: 1350,
    option_fee: 4000,
    lease_term_months: 24,
    interest_rate: null,
    balloon_months: null,
    raw_description:
      "Rent-to-own / lease option — your choice of structure. $4,000 option fee secures this 3 bed / 2 bath home at today's price. Rent is $1,350/mo with option to purchase at $215,000 anytime within 24 months. 20% of rent applies toward your down payment. Good condition, newer carpet and paint, fenced yard, 1-car garage. Motivated owner — open to either structure. Great for buyers who are 1-2 years away from bank approval.",
    parsed_terms: {
      financing_types: ["rent_to_own", "lease_option"],
      down_payment: null,
      monthly_payment: 1350,
      option_fee: 4000,
      lease_term_months: 24,
      interest_rate: null,
      balloon_months: null,
      confidence: 0.95,
    },
    photos: photos("rolling-hills", 3),
    contact_name: "Pam Wilson",
    contact_phone: "(307) 555-0834",
    contact_email: null,
    first_seen_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-009",
    source_url: "#",
    address: "2104 4-J Rd",
    normalized_address: "2104 4-j rd",
    city: "Gillette",
    state: "WY",
    zip: "82717",
    lat: 44.3123,
    lng: -105.5067,
    beds: 5,
    baths: 3.5,
    sqft: 3120,
    lot_size_sqft: 43560,
    year_built: 2012,
    price: 510000,
    financing_types: ["owner_carry"],
    down_payment: 50000,
    monthly_payment: 3200,
    option_fee: null,
    lease_term_months: null,
    interest_rate: 6.5,
    balloon_months: 120,
    raw_description:
      "Owner will carry at 6.5% — no bank required. $50,000 down on this stunning 5-bed executive home on a full 1-acre lot. Monthly payment of $3,200 on a 10-year balloon (120 months). Home features a gourmet kitchen, media room, home office, 3-car attached garage, and a 30x40 outbuilding. Horse-friendly zoning. Mountain views. Custom finishes throughout. Seller is a cash investor willing to carry for the right buyer. References required.",
    parsed_terms: {
      financing_types: ["owner_carry"],
      down_payment: 50000,
      monthly_payment: 3200,
      option_fee: null,
      lease_term_months: null,
      interest_rate: 6.5,
      balloon_months: 120,
      confidence: 0.97,
    },
    photos: photos("4j-rd", 5),
    contact_name: "Bill Carson",
    contact_phone: "(307) 555-0945",
    contact_email: "bill.carson@example.com",
    first_seen_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
  {
    source: "seed",
    source_id: "seed-010",
    source_url: "#",
    address: "445 Camel Dr",
    normalized_address: "445 camel dr",
    city: "Gillette",
    state: "WY",
    zip: "82716",
    lat: 44.2812,
    lng: -105.4756,
    beds: 2,
    baths: 1,
    sqft: 1050,
    lot_size_sqft: 5800,
    year_built: 1974,
    price: 155000,
    financing_types: ["seller_financing", "land_contract"],
    down_payment: 10000,
    monthly_payment: 850,
    option_fee: null,
    lease_term_months: null,
    interest_rate: 8.0,
    balloon_months: 60,
    raw_description:
      "Seller financing or land contract — investor selling this affordable 2 bed / 1 bath at a great price. $10,000 down, $850/mo at 8% on a 5-year balloon. Clean and move-in ready. New furnace 2022. Great for a first-time buyer or investor wanting easy entry into the market. Land contract option available — you get possession immediately, deed transfers when loan is paid off or refinanced. Call for showing.",
    parsed_terms: {
      financing_types: ["seller_financing", "land_contract"],
      down_payment: 10000,
      monthly_payment: 850,
      option_fee: null,
      lease_term_months: null,
      interest_rate: 8.0,
      balloon_months: 60,
      confidence: 0.92,
    },
    photos: photos("camel-dr", 3),
    contact_name: null,
    contact_phone: "(307) 555-1023",
    contact_email: null,
    first_seen_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    last_seen_at: new Date().toISOString(),
    is_active: true,
  },
];

async function seed() {
  console.log("Deleting existing seed rows...");
  const { error: delError } = await supabase
    .from("properties")
    .delete()
    .eq("source", "seed");

  if (delError) {
    console.error("Delete failed:", delError.message);
    process.exit(1);
  }

  console.log("Inserting 10 seed properties...");
  const { data, error } = await supabase
    .from("properties")
    .insert(PROPERTIES)
    .select("id, address");

  if (error) {
    console.error("Insert failed:", error.message);
    process.exit(1);
  }

  console.log(`\nInserted ${data?.length ?? 0} properties:`);
  data?.forEach((p) => console.log(`  • ${p.address} (${p.id})`));
  console.log("\nSeed complete.");
}

seed();
